drop table "PROFILE";
DROP TABLE "MESSAGE";

CREATE TABLE "PROFILE" (
	ID VARCHAR(100) NOT NULL,
	VISITAS NUMERIC(9) NOT NULL
);

CREATE TABLE "MESSAGE" (
	ID  VARCHAR(100) NOT NULL, 
	"USER" VARCHAR(100) NOT NULL, 
	CONTEUDO VARCHAR(400) NULL
)